services:
  - type: web
    name: ghana-health-ai
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MISTRAL_API_KEY
        sync: false
      - key: MISTRAL_CASE_STUDY_API_KEY
        sync: false
      - key: NPM_CONFIG_PRODUCTION
        value: false

databases:
  - name: ghana-health-ai-db
    databaseName: ghana_health_ai
    user: ghana_health_ai_user
    plan: free